DROP TABLE REPLY_ON_LOSTDETAIL;--실종 상세보기 게시판의 답변
DROP SEQUENCE REPLY_NO_SEQ;
DROP SEQUENCE REPLYSEQ;

--CREATE SEQUENCE REPLY_ORDER_SEQ NOCACHE;--REPLY_ORDER에 대한 시퀀스
--CREATE SEQUENCE LEV_SEQ     NOCACHE;--REPLYSEQ에 대한 시퀀스

CREATE TABLE REPLY_ON_LOSTDETAIL(
	BOARD_ID NUMBER NOT NULL,
	REPLY_ORDER   NUMBER CONSTRAINT PK_REPLY_ORDER PRIMARY KEY,
	NUM       NUMBER NOT NULL,
	LEV    NUMBER,
	LEV_SEQ NUMBER NOT NULL,
	DEPTH   NUMBER,--루트노드기준을 잡기 위함
	REPLYTAB NUMBER NOT NULL,
	ID       VARCHAR(50) NOT NULL,
	CONTENT  VARCHAR(2000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	LIKENO  NUMBER DEFAULT 0,
	BAN     NUMBER DEFAULT 0
);

SELECT * FROM REPLY_ON_LOSTDETAIL;

SELECT * FROM (SELECT ROWNUM RPROW, BOARD_ID, REPLY_ORDER, NUM, LEV, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN FROM (SELECT * FROM REPLY_ON_LOSTDETAIL)) WHERE RPROW BETWEEN 1 AND 30;

INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,1,1,0,1,NULL,0,'ADMIN','테스트글1','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,2,2,0,1,NULL,0,'ADMIN','테스트글2','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,3,3,0,1,NULL,0,'ADMIN','테스트글3','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,4,4,0,1,NULL,0,'ADMIN','테스트글4','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,5,5,0,1,NULL,0,'ADMIN','테스트글5','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,6,6,0,1,NULL,0,'ADMIN','테스트글6','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,7,7,0,1,NULL,0,'ADMIN','테스트글7','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,8,8,0,1,NULL,0,'ADMIN','테스트글8','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,9,9,0,1,NULL,0,'ADMIN','테스트글9','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,10,10,0,1,NULL,0,'ADMIN','테스트글10','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,11,11,0,1,NULL,0,'ADMIN','테스트글11','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,12,12,0,1,NULL,0,'ADMIN','테스트글12','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,13,13,0,1,NULL,0,'ADMIN','테스트글13','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,14,14,0,1,NULL,0,'ADMIN','테스트글14','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,15,15,0,1,NULL,0,'ADMIN','테스트글15','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,16,16,0,1,NULL,0,'ADMIN','테스트글16','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,17,17,0,1,NULL,0,'ADMIN','테스트글17','21/06/01',0,0);
INSERT INTO REPLY_ON_LOSTDETAIL
VALUES(1,18,18,0,1,NULL,0,'ADMIN','테스트글18','21/06/01',0,0);

UPDATE REPLY_ON_LOSTDETAIL
SET    LEV_SEQ=(LEV_SEQ+1)
WHERE  BOARD_ID=1 AND NUM=18 AND LEV=1 AND LEV_SEQ>1;


SELECT BOARD_ID, REPLY_ORDER, NUM, LEVEL, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR REPLY_ORDER= LEV
ORDER SIBLINGS BY NUM;

SELECT * 
FROM (SELECT ROWNUM ORD, BOARD_ID, REPLY_ORDER, NUM, LEVEL, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR REPLY_ORDER= LEV
ORDER SIBLINGS BY NUM)
WHERE NUM=1 AND (ORD BETWEEN 1 AND 30);


SELECT BOARD_ID, REPLY_ORDER, NUM, LEV, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=1  AND LEV=0 AND LEV_SEQ=1;

SELECT * 
FROM (SELECT ROWNUM ORD, BOARD_ID, REPLY_ORDER, NUM, LEVEL, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR REPLY_ORDER= LEV
ORDER SIBLINGS BY NUM)
WHERE NUM=1 AND (ORD BETWEEN 1 AND 30);


SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT BOARD_ID, REPLY_ORDER, NUM, LEVEL, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR REPLY_ORDER= LEV
ORDER SIBLINGS BY NUM) TARGET
WHERE NUM=1) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);
--형제 요소간 기준 변경
SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT BOARD_ID, REPLY_ORDER, NUM, LEV, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR REPLY_ORDER= LEV
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=18) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);

SELECT MAX(LEV_SEQ) FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=18 AND LEV=2;

SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT DISTINCT BOARD_ID, REPLY_ORDER, NUM, LEV, LEVEL, CONNECT_BY_ISLEAF LEAF, LEV_SEQ, DEPTH,REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH DEPTH IS NULL
CONNECT BY PRIOR LEV_SEQ=LEV
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=13) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);

SELECT * FROM REPLY_ON_LOSTDETAIL
WHERE NUM=10;
---
SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT DISTINCT BOARD_ID, REPLY_ORDER, NUM, LEV, LEV_SEQ, DEPTH,REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH DEPTH IS NULL
CONNECT BY NOCYCLE PRIOR LEV=DEPTH
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=10) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);
--------------------------
SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT BOARD_ID, REPLY_ORDER, NUM, LEV, LEVEL,LEV_SEQ, DEPTH,CONNECT_BY_ISLEAF ISLEAF, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH DEPTH IS NULL
CONNECT BY NOCYCLE PRIOR REPLY_ORDER=NUM
ORDER SIBLINGS BY DEPTH) TARGET
WHERE BOARD_ID=1 AND NUM=13) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);


UPDATE REPLY_ON_LOSTDETAIL
SET    LEV_SEQ = (LEV_SEQ+1)
WHERE  BOARD_ID=1 AND NUM=13 AND LEV=1 AND REPLYTAB>1;


SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT BOARD_ID, REPLY_ORDER, NUM, LEV, LEVEL,LEV_SEQ, DEPTH,CONNECT_BY_ISLEAF ISLEAF, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH DEPTH IS NULL
CONNECT BY NOCYCLE PRIOR REPLY_ORDER=NUM
ORDER SIBLINGS BY DEPTH, REPLYTAB) TARGET
WHERE BOARD_ID=1 AND NUM=13) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);

UPDATE REPLY_ON_LOSTDETAIL
SET    LEV_SEQ=(LEV_SEQ+1)
WHERE  BOARD_ID=1 AND NUM=13 AND LEV=1 AND REPLYTAB>1;


UPDATE REPLY_ON_LOSTDETAIL
SET    LEV_SEQ=(LEV_SEQ+1),
LEV=(SELECT MIN(LEV_SEQ) FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=13 AND LEV=1);



UPDATE REPLY_ON_LOSTDETAIL
SET    LEV=(LEV+1)
WHERE  BOARD_ID=1 AND NUM=16 AND LEV=1 AND LEV_SEQ < (SELECT MAX(LEV_SEQ) FROM REPLY_ON_LOSTDETAIL
WHERE BOARD_ID=1 AND NUM=16 AND LEV=1);


UPDATE REPLY_ON_LOSTDETAIL
SET    LEV_SEQ=(LEV_SEQ+1)
WHERE  BOARD_ID=1 AND NUM=18 AND LEV=1 AND LEV_SEQ>2;



UPDATE REPLY_ON_LOSTDETAIL
SET	   LEV=(LEV+1)
WHERE  BOARD_ID=1 AND
REPLY_ORDER < (SELECT MAX(REPLY_ORDER) FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=12 AND LEV=1) AND
NUM=12;

UPDATE REPLY_ON_LOSTDETAIL
SET    LEV=(LEV-1), LEV_SEQ=(LEV_SEQ+1)
WHERE  BOARD_ID=1 AND
NUM=12 AND
LEV > (SELECT DISTINCT LEV FROM REPLY_ON_LOSTDETAIL R1 WHERE BOARD_ID=1 AND NUM=12 AND LEV=1) AND
REPLY_ORDER > (SELECT MAX(REPLY_ORDER) FROM REPLY_ON_LOSTDETAIL R2 WHERE BOARD_ID=1 AND NUM=12 AND LEV=1);


SELECT REPLY_ORDER
FROM   REPLY_ON_LOSTDETAIL
WHERE  BOARD_ID=1 AND NUM=15;

SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT DISTINCT BOARD_ID, REPLY_ORDER, NUM, LEV, LEVEL, LEV_SEQ, DEPTH,REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH DEPTH IS NULL
CONNECT BY PRIOR LEV = DEPTH
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=14) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);

SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT DISTINCT BOARD_ID, REPLY_ORDER, NUM, LEV, LEVEL,LEV_SEQ, DEPTH,REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH DEPTH IS NULL
CONNECT BY PRIOR LEV = DEPTH
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=2) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);

SELECT LEV_SEQ FROM REPLY_ON_LOSTDETAIL R1 WHERE R1.LEV=1;

UPDATE REPLY_ON_LOSTDETAIL
SET	   LEV_SEQ = (SELECT LEV_SEQ FROM REPLY_ON_LOSTDETAIL R1 WHERE R1.BOARD_ID=1 AND R1.NUM=14 AND R1.LEV=0);


SELECT LEV_SEQ FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=13 AND LEV_SEQ=2;

UPDATE REPLY_ON_LOSTDETAIL
SET    LEV_SEQ=(LEV_SEQ+1)
WHERE  LEV=1
AND    BOARD_ID=1
AND    NUM = 13
AND    DEPTH
AND    LEV_SEQ > 1;


SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT DISTINCT BOARD_ID, REPLY_ORDER, NUM, LEV,LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR LEV_SEQ= LEV
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=12) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);




UPDATE REPLY_ON_LOSTDETAIL
SET    LEV_SEQ=LEV_SEQ+1
WHERE  LEV=(SELECT LEV FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=14 AND LEV=2) AND
REPLY_ORDER > (SELECT MAX(REPLY_ORDER) FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=14 AND LEV=2);

DELETE FROM REPLY_ON_LOSTDETAIL;

SELECT * FROM
(SELECT ROWNUM ORD, PROCESSED.* FROM
(SELECT TARGET.*
FROM (SELECT BOARD_ID, REPLY_ORDER, NUM, LEV, LEV_SEQ, REPLYTAB, ID, CONTENT, REGDATE, LIKENO, BAN
FROM REPLY_ON_LOSTDETAIL
START WITH LEV=0
CONNECT BY PRIOR REPLY_ORDER= LEV
ORDER SIBLINGS BY LEV_SEQ) TARGET
WHERE NUM=14) PROCESSED)
WHERE (ORD BETWEEN 1 AND 30);

SELECT MAX(LEV) FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=18;
SELECT LEV_SEQ FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=18;

UPDATE REPLY_ON_LOSTDETAIL R1
SET    LEV=(SELECT LEV_SEQ FROM REPLY_ON_LOSTDETAIL WHERE LEV_SEQ=R1.LEV_SEQ);

UPDATE REPLY_ON_LOSTDETAIL
SET    LEV = (LEV-1)
WHERE  (LEV,LEV_SEQ) IN (SELECT LEV, LEV_SEQ FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=14 AND LEV=2 AND LEV_SEQ=3)
AND    REPLY_ORDER > (SELECT MIN(REPLY_ORDER) FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=14 AND LEV=2);


UPDATE REPLY_ON_LOSTDETAIL
SET    LEV_SEQ=(LEV_SEQ+1)
WHERE  LEV > (SELECT LEV FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=14 AND LEV=1)
AND LEV_SEQ > (SELECT LEV_SEQ FROM REPLY_ON_LOSTDETAIL WHERE BOARD_ID=1 AND NUM=14 AND LEV = 1);
